name: Upload Images

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read-write
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v2
      with:
        python-version: 3
    - name: install
      run: |
        pip install boto3 requests pyjwt
    - name: run
      run: |
        python .github/workflows/list.py
